### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.channels' doesn't exist (SQL: select * from `channels`)

### ISSUE THREAD

**Issue by aboutsam** [MirShaon/Forum-Advanced#1]
When i run "composer install" i got this error message:

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover


  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.channels' d
  oesn't exist (SQL: select * from `channels`)



  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.channels' d
  oesn't exist


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

In database folder the file with name "2017_11_10_130554_create_channels_table.php" exists.

**Comment by MirShaon** [comment]
please update your composer then try it, it will resolve your problem.

**Comment by remymumoh** [comment]
it is a tedious process but try and delete all the models and recreate them again and copy the relevant code to the relevant models and also add the same data to the database migrations. that should work. dont know why artisan is misbehaving

**Comment by MirShaon** [comment]
Can you please update your composer? then let me know.

**Comment by hamza-mostafa** [comment]
Hi @MirShaon .. the same issue with me actually, even after `composer install` and `composer update`
I also noticed this when I `composer install` and specifically at this point `@php artisan package:discover`

`In Connection.php line 664:
                                                                               
  `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forum.channels'     `
  `doesn't exist (SQL: select * from `channels`)                                                           `
                                                                               

  `In Connection.php line 326:                                                                                      `
    `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forum.channels'   `
    `doesn't exist                                                                                                            `

**Comment by MirShaon** [comment]
Thanks @hamza-mostafa
